local itenManager = {}

-- https://tomat.dev/undertale/items
local items = {
    {id = 1, name = 'Monster Candy', shortName = 'MnstrCndy',vdescription = 'Has a distinct, non-licorice flavor.', stat = 10, type = 'consumable'},
    {id = 2, name = 'Monster Candy', shortName = 'MnstrCndy',vdescription = 'Has a distinct, non-licorice flavor.', stat = 10, type = 'consumable'},
    {id = 3, name = 'Monster Candy', shortName = 'MnstrCndy',vdescription = 'Has a distinct, non-licorice flavor.', stat = 10, type = 'consumable'},
    {id = 4, name = 'Monster Candy', shortName = 'MnstrCndy',vdescription = 'Has a distinct, non-licorice flavor.', stat = 10, type = 'consumable'},
    {id = 5, name = 'Monster Candy', shortName = 'MnstrCndy',vdescription = 'Has a distinct, non-licorice flavor.', stat = 10, type = 'consumable'},
    {id = 6, name = 'Monster Candy', shortName = 'MnstrCndy',vdescription = 'Has a distinct, non-licorice flavor.', stat = 10, type = 'consumable'},
    {id = 7, name = 'Monster Candy', shortName = 'MnstrCndy',vdescription = 'Has a distinct, non-licorice flavor.', stat = 10, type = 'consumable'},
    {id = 8, name = 'Monster Candy', shortName = 'MnstrCndy',vdescription = 'Has a distinct, non-licorice flavor.', stat = 10, type = 'consumable'},
    {id = 9, name = 'Monster Candy', shortName = 'MnstrCndy',vdescription = 'Has a distinct, non-licorice flavor.', stat = 10, type = 'consumable'},
    {id = 10, name = 'Monster Candy', shortName = 'MnstrCndy',vdescription = 'Has a distinct, non-licorice flavor.', stat = 10, type = 'consumable'},
    {id = 11, name = 'Monster Candy', shortName = 'MnstrCndy',vdescription = 'Has a distinct, non-licorice flavor.', stat = 10, type = 'consumable'},
    {id = 12, name = 'Monster Candy', shortName = 'MnstrCndy',vdescription = 'Has a distinct, non-licorice flavor.', stat = 10, type = 'consumable'},
    {id = 13, name = 'Monster Candy', shortName = 'MnstrCndy',vdescription = 'Has a distinct, non-licorice flavor.', stat = 10, type = 'consumable'},
    {id = 14, name = 'Monster Candy', shortName = 'MnstrCndy',vdescription = 'Has a distinct, non-licorice flavor.', stat = 10, type = 'consumable'},
    {id = 15, name = 'Monster Candy', shortName = 'MnstrCndy',vdescription = 'Has a distinct, non-licorice flavor.', stat = 10, type = 'consumable'},
    {id = 16, name = 'Monster Candy', shortName = 'MnstrCndy',vdescription = 'Has a distinct, non-licorice flavor.', stat = 10, type = 'consumable'},
    {id = 17, name = 'Monster Candy', shortName = 'MnstrCndy',vdescription = 'Has a distinct, non-licorice flavor.', stat = 10, type = 'consumable'},
    {id = 18, name = 'Monster Candy', shortName = 'MnstrCndy',vdescription = 'Has a distinct, non-licorice flavor.', stat = 10, type = 'consumable'},
    {id = 19, name = 'Monster Candy', shortName = 'MnstrCndy',vdescription = 'Has a distinct, non-licorice flavor.', stat = 10, type = 'consumable'},
    {id = 20, name = 'Monster Candy', shortName = 'MnstrCndy',vdescription = 'Has a distinct, non-licorice flavor.', stat = 10, type = 'consumable'},
    {id = 21, name = 'Monster Candy', shortName = 'MnstrCndy',vdescription = 'Has a distinct, non-licorice flavor.', stat = 10, type = 'consumable'},
    {id = 22, name = 'Monster Candy', shortName = 'MnstrCndy',vdescription = 'Has a distinct, non-licorice flavor.', stat = 10, type = 'consumable'},
    {id = 23, name = 'Monster Candy', shortName = 'MnstrCndy',vdescription = 'Has a distinct, non-licorice flavor.', stat = 10, type = 'consumable'},
    {id = 24, name = 'Monster Candy', shortName = 'MnstrCndy',vdescription = 'Has a distinct, non-licorice flavor.', stat = 10, type = 'consumable'},
    {id = 25, name = 'Monster Candy', shortName = 'MnstrCndy',vdescription = 'Has a distinct, non-licorice flavor.', stat = 10, type = 'consumable'},
    {id = 26, name = 'Monster Candy', shortName = 'MnstrCndy',vdescription = 'Has a distinct, non-licorice flavor.', stat = 10, type = 'consumable'},
    {id = 27, name = 'Monster Candy', shortName = 'MnstrCndy',vdescription = 'Has a distinct, non-licorice flavor.', stat = 10, type = 'consumable'},
    {id = 28, name = 'Monster Candy', shortName = 'MnstrCndy',vdescription = 'Has a distinct, non-licorice flavor.', stat = 10, type = 'consumable'},
    {id = 29, name = 'Monster Candy', shortName = 'MnstrCndy',vdescription = 'Has a distinct, non-licorice flavor.', stat = 10, type = 'consumable'},
    {id = 30, name = 'Monster Candy', shortName = 'MnstrCndy',vdescription = 'Has a distinct, non-licorice flavor.', stat = 10, type = 'consumable'},
    {id = 31, name = 'Monster Candy', shortName = 'MnstrCndy',vdescription = 'Has a distinct, non-licorice flavor.', stat = 10, type = 'consumable'},
    {id = 32, name = 'Monster Candy', shortName = 'MnstrCndy',vdescription = 'Has a distinct, non-licorice flavor.', stat = 10, type = 'consumable'},
    {id = 33, name = 'Monster Candy', shortName = 'MnstrCndy',vdescription = 'Has a distinct, non-licorice flavor.', stat = 10, type = 'consumable'},
    {id = 34, name = 'Monster Candy', shortName = 'MnstrCndy',vdescription = 'Has a distinct, non-licorice flavor.', stat = 10, type = 'consumable'},
    {id = 35, name = 'Monster Candy', shortName = 'MnstrCndy',vdescription = 'Has a distinct, non-licorice flavor.', stat = 10, type = 'consumable'},
    {id = 36, name = 'Monster Candy', shortName = 'MnstrCndy',vdescription = 'Has a distinct, non-licorice flavor.', stat = 10, type = 'consumable'},
    {id = 37, name = 'Monster Candy', shortName = 'MnstrCndy',vdescription = 'Has a distinct, non-licorice flavor.', stat = 10, type = 'consumable'},
    {id = 38, name = 'Monster Candy', shortName = 'MnstrCndy',vdescription = 'Has a distinct, non-licorice flavor.', stat = 10, type = 'consumable'},
    {id = 39, name = 'Monster Candy', shortName = 'MnstrCndy',vdescription = 'Has a distinct, non-licorice flavor.', stat = 10, type = 'consumable'},
    {id = 40, name = 'Monster Candy', shortName = 'MnstrCndy',vdescription = 'Has a distinct, non-licorice flavor.', stat = 10, type = 'consumable'},
    {id = 41, name = 'Monster Candy', shortName = 'MnstrCndy',vdescription = 'Has a distinct, non-licorice flavor.', stat = 10, type = 'consumable'},
    {id = 42, name = 'Monster Candy', shortName = 'MnstrCndy',vdescription = 'Has a distinct, non-licorice flavor.', stat = 10, type = 'consumable'},
    {id = 43, name = 'Monster Candy', shortName = 'MnstrCndy',vdescription = 'Has a distinct, non-licorice flavor.', stat = 10, type = 'consumable'},
    {id = 44, name = 'Monster Candy', shortName = 'MnstrCndy',vdescription = 'Has a distinct, non-licorice flavor.', stat = 10, type = 'consumable'},
    {id = 45, name = 'Monster Candy', shortName = 'MnstrCndy',vdescription = 'Has a distinct, non-licorice flavor.', stat = 10, type = 'consumable'},
    {id = 46, name = 'Monster Candy', shortName = 'MnstrCndy',vdescription = 'Has a distinct, non-licorice flavor.', stat = 10, type = 'consumable'},
    {id = 47, name = 'Monster Candy', shortName = 'MnstrCndy',vdescription = 'Has a distinct, non-licorice flavor.', stat = 10, type = 'consumable'},
    {id = 48, name = 'Monster Candy', shortName = 'MnstrCndy',vdescription = 'Has a distinct, non-licorice flavor.', stat = 10, type = 'consumable'},
    {id = 49, name = 'Monster Candy', shortName = 'MnstrCndy',vdescription = 'Has a distinct, non-licorice flavor.', stat = 10, type = 'consumable'},
    {id = 50, name = 'Monster Candy', shortName = 'MnstrCndy',vdescription = 'Has a distinct, non-licorice flavor.', stat = 10, type = 'consumable'},
    {id = 51, name = 'Monster Candy', shortName = 'MnstrCndy',vdescription = 'Has a distinct, non-licorice flavor.', stat = 10, type = 'consumable'},
    {id = 52, name = 'Monster Candy', shortName = 'MnstrCndy',vdescription = 'Has a distinct, non-licorice flavor.', stat = 10, type = 'consumable'},
    {id = 53, name = 'Monster Candy', shortName = 'MnstrCndy',vdescription = 'Has a distinct, non-licorice flavor.', stat = 10, type = 'consumable'},
    {id = 54, name = 'Monster Candy', shortName = 'MnstrCndy',vdescription = 'Has a distinct, non-licorice flavor.', stat = 10, type = 'consumable'},
    {id = 55, name = 'Monster Candy', shortName = 'MnstrCndy',vdescription = 'Has a distinct, non-licorice flavor.', stat = 10, type = 'consumable'},
    {id = 56, name = 'Monster Candy', shortName = 'MnstrCndy',vdescription = 'Has a distinct, non-licorice flavor.', stat = 10, type = 'consumable'},
    {id = 57, name = 'Monster Candy', shortName = 'MnstrCndy',vdescription = 'Has a distinct, non-licorice flavor.', stat = 10, type = 'consumable'},
    {id = 58, name = 'Monster Candy', shortName = 'MnstrCndy',vdescription = 'Has a distinct, non-licorice flavor.', stat = 10, type = 'consumable'},
    {id = 59, name = 'Monster Candy', shortName = 'MnstrCndy',vdescription = 'Has a distinct, non-licorice flavor.', stat = 10, type = 'consumable'}
}


return itemManager